### PR TITLE
Allow frames with payload size bigger than 64KB

### PR DESCRIPTION
**Pull request by jcelaya**
These patches implement/fix sending and receiving frames with a payload of more than 64KB. Theoretically, the maximum should be 0x8000000000000000, but on 32-bit platforms it has been capped down to 0x80000000 because it is unclear how to easily define a portable 64-bit long int. Since that limit is already high enough for most situations, this problem can be fixed later.

### CODE REVIEW

**Comment by jcelaya** [comment]
Hi, isn't anybody looking into this? Is there any problem?

**Comment by francisbrosnan** [comment]
Hi, 
I've been out of office some days...I'll review this asap...
Best Regards,

**Comment by jcelaya** [comment]
Thank you, Francis

**Comment by francisbrosnan** [comment]
Hello Javier,
The patch looks good. I need more time to test it across all supported platforms...but let's continue. I'll be doing more tests...in the meantime I'll merge the patch so we can all continue,
Thanks you very much for taking your time Javier,
Best Regards!

**Pull request merged**
