### PR TITLE
Porting ipv6 support from Webpa Client nopoll code.

### PR DESCRIPTION
**Pull request by manderiasian**

### CODE REVIEW

**Comment by manderiasian** [comment]
Will this pull request be done, or is there an issue with it? Let me know please when you can.

**Comment by francisbrosnan** [comment]
Hello manderiasian,
Thanks for your PR. I haven't had time to review it. I hope to do it soon. I'll keep you updated,
Best Regards,

**Comment by manderiasian** [comment]
Waiting for the pull request, I understand you are busy, if you can provide a ball-park time estimate I appreciate it. Regards.

**Comment by francisbrosnan** [comment]
Hello Manderiasian,

Again, thanks for taking your time for the patch and reporting.
Just let you know I'm working on it, checking it with the different platforms we have 
to support (around 14). I'll take some time but I think I going to have it soon. 

There are several formatting issues but I can handle them after checking everything
is ok (especially with older linux, freebsd and windows xp versions).

I'll let you know my progress,
Best Regards,

**Comment by francisbrosnan** [comment]
Hello,

The patch provided does not work in all platforms we have to support. I haven't checked all of them. I stopped on the first two tests (debian lenny i686/amd64). 

I started reviewing the patch and what I see its that it provides transparent ipv4/ipv6 over the same API: first that connects will work. Even though it is an attractive idea, we prefer to provide specific APIs for ipv4 and ipv6 so the user have full control over what's happening, and, in essence, having these, you can easily implement the transparent behaviour of first-ipv4-then-ipv6-if-fails (or whatever combination you are trying to).

I'll add ipv6 apis righ away so you can implement all this on top of it. 

I'm sorry but I can accept the patch,
Thanks for your taking your time,
Best Regards,

**Comment by manderiasian** [comment]
Thanks for your comments, we had done testing of the client code and did not apparently see the issues you see.  In any case, if u do get a chance please let us know what specific tests weill need to run if we do have any future enhancements or modifications, i uI do run the test that comes with the package and it seemed to work without an issue; however I am sure u are correct. Thanks again for taking the time to look at this patch.

**Comment by francisbrosnan** [comment]
Dear,

Just let you know I've just pushed an update (rev 305) that adds support for IPv6, adding new apis, keeping previous ones in form and essence (everything checked).

Hope you find them useful for your scenario,
Again, thanks for reporting,
Best Regards,

**Pull request closed without merging**
